#!/bin/bash
#
# Proftpd
# I'm now symlinking the docbook source to faq.sgml
#
export BASE="$HOME/Proftpd/"
export ROOT="$BASE/www.pdd/"
export FTP="$BASE/ftp.pdd/proftpd/"
export FAQ="faq"
export SGMLSRC="$BASE/FAQ/$FAQ.sgml"
##
## Test to see if we can find a stylesheet using a
## provided path
##
if [ -f $DSSSL_STYLESHEET_PATH/html/docbook.dsl ]
then
  DSL="$DSSSL_STYLESHEET_PATH/html/docbook.dsl"
else
  # Fall back to a hardcoded default
  DSL="/usr/lib/sgml/stylesheet/dsssl/docbook/nwalsh/html/docbook.dsl"
fi
##
##
##
mkdir -p $BASE/FAQ/html/
if [ -d $BASE/FAQ/html/ ]
then
	cd $BASE/FAQ/html/
	rm -rfv *
else
	echo "Problem with html output directory"
	exit
fi

# Build the single file
echo -n "Building FAQ: "
echo -n "single "
jade -t sgml -V nochunks -d $DSL ${SGMLSRC} > ${FAQ}_full.html

# Build the linked file
echo -n "linked "
mkdir linked
cd linked
jade -t sgml -d $DSL ${SGMLSRC}
cd ..

# PDF file
echo -n "pdf "
htmldoc --webpage -f ${FAQ}.pdf ${FAQ}_full.html

# Postscript
echo -n "ps "
htmldoc --webpage -f ${FAQ}.ps ${FAQ}_full.html

## Install
cd $BASE/FAQ/html
mkdir -p $BASE/www.proftpd.org/docs/faq
rsync -av . $BASE/www.proftpd.org/docs/faq
#
# End...
#
